FROM node:20

WORKDIR /app

# Copy dependency files first
COPY app/package*.json ./
RUN npm install

# Copy the rest of the application code
COPY app/ .

# EXPOSE 3000
# ENTRYPOINT ["npm", "start"]
CMD ["npm", "start"]
